#!/usr/bin/env python3
"""Smoke tests for the llm-guidelines skill bundle.

This bundle is regenerated by `generate-skill.sh` in the upstream
llm-guidelines-website repo. These tests guard against the failure mode
documented in CLAUDE.md: a release where the `version` fields desync from
the bundle's content (e.g., marketplace.json still declares the previous
revision), causing `/plugin` to report "already at the latest" for users
on stale content.

Tests run with the stdlib only — no YAML library, no network, no install
step required. Frontmatter is parsed manually (single-line key: value).

Exits 0 if all pass; non-zero on the first failure (with a summary).
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CLAUDE_MARKETPLACE = ROOT / '.claude-plugin' / 'marketplace.json'
CODEX_MARKETPLACE = ROOT / '.agents' / 'plugins' / 'marketplace.json'
PLUGIN_DIR = ROOT / 'plugins' / 'llm-guidelines'
CLAUDE_PLUGIN_JSON = PLUGIN_DIR / '.claude-plugin' / 'plugin.json'
CODEX_PLUGIN_JSON = PLUGIN_DIR / '.codex-plugin' / 'plugin.json'
SKILLS_DIR = PLUGIN_DIR / 'skills'
COMMANDS_DIR = PLUGIN_DIR / 'commands'
SKILL_DIR = SKILLS_DIR / 'llm-guidelines'
REFS_DIR = SKILL_DIR / 'references'

EXPECTED_CLAUDE_VERSION = '2026.06_rev2'
VERSION_RE = re.compile(r'^\d{4}\.\d{2}(_rev\d+)?$')
SEMVER_RE = re.compile(r'^\d+\.\d+\.\d+$')


def read_frontmatter(path):
    """Return dict of frontmatter keys from a Markdown file.

    Supports the simple `key: value` form the bundle uses, plus one level
    of indented nesting for mapping values (used for the Agent Skills
    spec's `metadata:` block). Quoted scalars have their surrounding
    quotes stripped. Raises AssertionError if the file is missing a
    frontmatter block.
    """
    text = path.read_text(encoding='utf-8')
    assert text.startswith('---\n'), f"{path}: missing opening '---' fence"
    end = text.find('\n---\n', 4)
    assert end != -1, f"{path}: missing closing '---' fence"
    block = text[4:end]
    fm = {}
    current_parent = None
    for line in block.split('\n'):
        if not line.strip():
            continue
        assert ':' in line, f"{path}: malformed frontmatter line {line!r}"
        if line.startswith((' ', '\t')) and current_parent is not None:
            k, _, v = line.partition(':')
            fm[current_parent][k.strip()] = _strip_quotes(v.strip())
            continue
        k, _, v = line.partition(':')
        v = v.strip()
        if v == '':
            fm[k.strip()] = {}
            current_parent = k.strip()
        else:
            fm[k.strip()] = _strip_quotes(v)
            current_parent = None
    return fm


def _strip_quotes(s):
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        return s[1:-1]
    return s


def markdown_links(text):
    """Yield (label, target) for every [label](target) link."""
    for m in re.finditer(r'\[([^\]]+)\]\(([^)]+)\)', text):
        yield m.group(1), m.group(2)


def bundle_version():
    return (ROOT / 'VERSION').read_text(encoding='utf-8').strip()


def codex_semver_for(version):
    m = re.match(r'^(\d{4})\.(\d{2})(?:_rev(\d+))?$', version)
    assert m, f"cannot map {version!r} to Codex semver"
    year, month, revision = m.groups()
    return f"{year}.{int(month)}.{int(revision or 0)}"


# ---------- version coherence ----------

def test_version_file_format():
    v = bundle_version()
    assert VERSION_RE.match(v), f"VERSION {v!r} does not match YYYY.MM[_revN]"
    assert v == EXPECTED_CLAUDE_VERSION, \
        f"VERSION {v!r} != expected release {EXPECTED_CLAUDE_VERSION!r}"


def test_plugin_json_version_matches():
    p = CLAUDE_PLUGIN_JSON
    data = json.loads(p.read_text(encoding='utf-8'))
    assert data.get('name') == 'llm-guidelines', f"{p}: wrong name {data.get('name')!r}"
    assert data.get('version') == bundle_version(), \
        f"{p}: version {data.get('version')!r} != VERSION {bundle_version()!r}"
    for required in ('description', 'license'):
        assert data.get(required), f"{p}: missing or empty {required!r}"


def test_marketplace_json_version_matches():
    p = CLAUDE_MARKETPLACE
    data = json.loads(p.read_text(encoding='utf-8'))
    assert data.get('name') == 'llm-guidelines', \
        f"{p}: wrong marketplace name {data.get('name')!r}"
    plugins = data.get('plugins') or []
    assert len(plugins) == 1, f"{p}: expected 1 plugin entry, got {len(plugins)}"
    entry = plugins[0]
    assert entry.get('name') == 'llm-guidelines', \
        f"{p}: wrong plugin name {entry.get('name')!r}"
    assert entry.get('version') == bundle_version(), \
        f"{p}: version {entry.get('version')!r} != VERSION {bundle_version()!r} " \
        f"(this is exactly the desync that broke 2026.05_rev10)"
    assert entry.get('source') == './plugins/llm-guidelines', \
        f"{p}: wrong source {entry.get('source')!r}"


def test_codex_plugin_json_version_and_shape():
    p = CODEX_PLUGIN_JSON
    data = json.loads(p.read_text(encoding='utf-8'))
    expected = codex_semver_for(bundle_version())
    assert data.get('name') == 'llm-guidelines', f"{p}: wrong name {data.get('name')!r}"
    assert data.get('version') == expected, \
        f"{p}: version {data.get('version')!r} != expected Codex semver {expected!r}"
    assert SEMVER_RE.match(data.get('version', '')), \
        f"{p}: version {data.get('version')!r} is not strict semver"
    assert data.get('skills') == './skills/', \
        f"{p}: skills {data.get('skills')!r} != './skills/'"
    for required in ('description', 'homepage', 'repository', 'license'):
        assert data.get(required), f"{p}: missing or empty {required!r}"
    author = data.get('author') or {}
    assert author.get('name'), f"{p}: missing author.name"
    interface = data.get('interface') or {}
    required_interface = (
        'displayName',
        'shortDescription',
        'longDescription',
        'developerName',
        'category',
        'capabilities',
        'websiteURL',
        'defaultPrompt',
    )
    for required in required_interface:
        assert interface.get(required), f"{p}: missing or empty interface.{required}"
    assert interface.get('category') == 'Research', \
        f"{p}: interface.category {interface.get('category')!r} != 'Research'"


def test_codex_marketplace_shape():
    p = CODEX_MARKETPLACE
    data = json.loads(p.read_text(encoding='utf-8'))
    assert data.get('name') == 'se-uhd', f"{p}: wrong name {data.get('name')!r}"
    interface = data.get('interface') or {}
    assert interface.get('displayName') == 'SE UHD', \
        f"{p}: wrong displayName {interface.get('displayName')!r}"
    plugins = data.get('plugins') or []
    assert len(plugins) == 1, f"{p}: expected 1 plugin entry, got {len(plugins)}"
    entry = plugins[0]
    assert entry.get('name') == 'llm-guidelines', \
        f"{p}: wrong plugin name {entry.get('name')!r}"
    assert entry.get('source') == {
        'source': 'local',
        'path': './plugins/llm-guidelines',
    }, f"{p}: wrong source {entry.get('source')!r}"
    assert entry.get('policy') == {
        'installation': 'AVAILABLE',
        'authentication': 'ON_INSTALL',
    }, f"{p}: wrong policy {entry.get('policy')!r}"
    assert entry.get('category') == 'Research', \
        f"{p}: category {entry.get('category')!r} != 'Research'"


def test_skill_md_versions_match():
    skill = SKILL_DIR / 'SKILL.md'
    fm = read_frontmatter(skill)
    assert fm.get('name') == 'llm-guidelines', \
        f"{skill}: frontmatter name {fm.get('name')!r} != 'llm-guidelines'"
    metadata = fm.get('metadata') or {}
    assert metadata.get('version') == bundle_version(), \
        f"{skill}: metadata.version {metadata.get('version')!r} != VERSION {bundle_version()!r}"
    assert fm.get('description'), f"{skill}: missing description"
    assert fm.get('license'), f"{skill}: missing license"


def test_agents_files_point_to_claude_md():
    candidates = [ROOT / 'AGENTS.md']
    website_agents = ROOT.parent / 'AGENTS.md'
    if (ROOT.parent / 'generate-skill.sh').is_file() and website_agents.is_file():
        candidates.append(website_agents)
    for p in candidates:
        text = p.read_text(encoding='utf-8')
        assert '[CLAUDE.md](CLAUDE.md)' in text, \
            f"{p}: does not point Codex agents to CLAUDE.md"


# ---------- structural completeness ----------

def test_skills_and_commands_present():
    """One skill (`llm-guidelines`) backed by two slash commands (`explore`,
    `review`). The slash commands route into modes of the single skill."""
    skill_names = {p.name for p in SKILLS_DIR.iterdir() if (p / 'SKILL.md').is_file()}
    assert skill_names == {'llm-guidelines'}, \
        f"expected exactly {{llm-guidelines}}, got {sorted(skill_names)}"
    command_names = {p.stem for p in COMMANDS_DIR.glob('*.md')}
    assert command_names == {'explore', 'review'}, \
        f"expected exactly {{explore, review}}, got {sorted(command_names)}"
    for cmd_name in ('explore', 'review'):
        body = (COMMANDS_DIR / f'{cmd_name}.md').read_text(encoding='utf-8')
        assert '`llm-guidelines`' in body, \
            f"commands/{cmd_name}.md: does not name the llm-guidelines skill"


def test_references_required_files_exist():
    required = [
        REFS_DIR / 'scope.md',
        REFS_DIR / 'checklist.md',
        REFS_DIR / 'explore.md',
        REFS_DIR / 'review.md',
    ]
    for p in required:
        assert p.is_file(), f"missing reference file: {p.relative_to(ROOT)}"
    guidelines = list((REFS_DIR / 'guidelines').glob('*.md'))
    assert len(guidelines) == 8, \
        f"expected 8 guideline files, got {len(guidelines)}: " \
        f"{[g.name for g in guidelines]}"
    study_types = list((REFS_DIR / 'study-types').glob('*.md'))
    # 7 study types + advantages-and-challenges + two umbrella entries
    # ("llms-as-tools-for-software-engineering-researchers" and
    # "llms-as-tools-for-software-engineers") = 10 files total.
    assert len(study_types) == 10, \
        f"expected 10 study-type files, got {len(study_types)}: " \
        f"{[s.name for s in study_types]}"


# ---------- link health (internal only — no network) ----------

def test_skill_md_internal_links_resolve():
    """Every `references/...` link from SKILL.md, and every `./...` or
    `../...` link from a references/*.md, must point to a real file."""
    broken = []

    # SKILL.md links point into references/.
    skill = SKILL_DIR / 'SKILL.md'
    text = skill.read_text(encoding='utf-8')
    for label, target in markdown_links(text):
        path_part = target.split('#', 1)[0]
        if not path_part.startswith('references/'):
            continue
        resolved = (skill.parent / path_part).resolve()
        if not resolved.is_file():
            broken.append(f"{skill.relative_to(ROOT)}: [{label}]({target}) -> "
                          f"{resolved} (not found)")

    # references/{explore,review}.md link sideways (./guidelines/..., ./scope.md, ../SKILL.md).
    for mode_name in ('explore', 'review'):
        mode_file = REFS_DIR / f'{mode_name}.md'
        mtext = mode_file.read_text(encoding='utf-8')
        for label, target in markdown_links(mtext):
            path_part = target.split('#', 1)[0]
            if not (path_part.startswith('./') or path_part.startswith('../')):
                continue
            resolved = (mode_file.parent / path_part).resolve()
            if not resolved.is_file():
                broken.append(f"{mode_file.relative_to(ROOT)}: [{label}]({target}) -> "
                              f"{resolved} (not found)")

    assert not broken, "broken internal links:\n  " + "\n  ".join(broken)


def test_no_absolute_website_links_leaked_into_references():
    """The generator rewrites `/guidelines/<slug>/` etc. to relative paths
    inside references/. A leak here means the rewrite step regressed."""
    leaks = []
    for md in REFS_DIR.rglob('*.md'):
        text = md.read_text(encoding='utf-8')
        for label, target in markdown_links(text):
            if re.match(r'^/(guidelines|study-types|scope|checklist)/', target):
                leaks.append(f"{md.relative_to(ROOT)}: [{label}]({target})")
    assert not leaks, "absolute website paths leaked into bundle:\n  " + "\n  ".join(leaks)


def test_review_instructions_resolve_linter_across_clients():
    review = REFS_DIR / 'review.md'
    text = review.read_text(encoding='utf-8')
    assert '${CLAUDE_SKILL_DIR}/scripts/lint_markdown.py' in text, \
        f"{review}: missing Claude skill-dir linter candidate"
    assert 'plugins/llm-guidelines/skills/llm-guidelines/scripts/lint_markdown.py' in text, \
        f"{review}: missing checkout linter candidate"
    assert '${CODEX_HOME:-$HOME/.codex}/plugins/cache' in text, \
        f"{review}: missing Codex plugin-cache linter candidate"
    assert 'If no linter is found, continue without the lint loop' in text, \
        f"{review}: missing no-linter fallback"
    assert 'python3 ${CLAUDE_SKILL_DIR}/scripts/lint_markdown.py --fix' not in text, \
        f"{review}: still depends only on CLAUDE_SKILL_DIR"


def test_optional_codex_cli_marketplace_smoke():
    codex = shutil.which('codex')
    if not codex:
        print('SKIP  test_optional_codex_cli_marketplace_smoke: codex not installed')
        return

    tmp_root = '/private/tmp' if Path('/private/tmp').is_dir() else None
    with tempfile.TemporaryDirectory(prefix='llm-guidelines-codex-', dir=tmp_root) as tmp:
        env = os.environ.copy()
        codex_home = Path(tmp) / 'codex-home'
        codex_home.mkdir()
        env['CODEX_HOME'] = str(codex_home)
        add = subprocess.run(
            [codex, 'plugin', 'marketplace', 'add', str(ROOT)],
            cwd=ROOT,
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=60,
        )
        assert add.returncode == 0, \
            "codex marketplace add failed:\nSTDOUT:\n{}\nSTDERR:\n{}".format(
                add.stdout, add.stderr
            )
        listed = subprocess.run(
            [codex, 'plugin', 'list', '--marketplace', 'se-uhd'],
            cwd=ROOT,
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=60,
        )
        assert listed.returncode == 0, \
            "codex plugin list failed:\nSTDOUT:\n{}\nSTDERR:\n{}".format(
                listed.stdout, listed.stderr
            )
        output = f"{listed.stdout}\n{listed.stderr}"
        listed_plugin = (
            'llm-guidelines@se-uhd' in output
            or re.search(r'\bllm-guidelines\b.*\bse-uhd\b', output)
            or re.search(r'\bse-uhd\b.*\bllm-guidelines\b', output)
        )
        assert listed_plugin, \
            f"codex plugin list did not show llm-guidelines@se-uhd:\n{output}"


# ---------- runner ----------

TESTS = [
    test_version_file_format,
    test_plugin_json_version_matches,
    test_marketplace_json_version_matches,
    test_codex_plugin_json_version_and_shape,
    test_codex_marketplace_shape,
    test_skill_md_versions_match,
    test_agents_files_point_to_claude_md,
    test_skills_and_commands_present,
    test_references_required_files_exist,
    test_skill_md_internal_links_resolve,
    test_no_absolute_website_links_leaked_into_references,
    test_review_instructions_resolve_linter_across_clients,
    test_optional_codex_cli_marketplace_smoke,
]


def main():
    failed = 0
    for t in TESTS:
        try:
            t()
            print(f"PASS  {t.__name__}")
        except AssertionError as e:
            print(f"FAIL  {t.__name__}: {e}", file=sys.stderr)
            failed += 1
        except Exception as e:
            print(f"ERROR {t.__name__}: {type(e).__name__}: {e}", file=sys.stderr)
            failed += 1
    if failed:
        print(f"\n{failed}/{len(TESTS)} failure(s)", file=sys.stderr)
        return 1
    print(f"\nAll {len(TESTS)} tests passed.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
