#!/usr/bin/env python3
"""Smoke tests for the llm-guidelines skill bundle.

This bundle is regenerated by `generate-skill.sh` in the upstream
llm-guidelines-website repo. These tests guard against the failure mode
documented in CLAUDE.md: a release where the `version` fields desync from
the bundle's content (e.g., marketplace.json still declares the previous
revision), causing `/plugin` to report "already at the latest" for users
on stale content.

Tests run with the stdlib only — no YAML library, no network, no install
step required. Frontmatter is parsed manually (single-line key: value).

Exits 0 if all pass; non-zero on the first failure (with a summary).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
PLUGIN_DIR = ROOT / 'plugins' / 'llm-guidelines'
SKILLS_DIR = PLUGIN_DIR / 'skills'
COMMANDS_DIR = PLUGIN_DIR / 'commands'
SHARED_DIR = PLUGIN_DIR / 'shared'

VERSION_RE = re.compile(r'^\d{4}\.\d{2}(_rev\d+)?$')


def read_frontmatter(path):
    """Return dict of frontmatter keys from a Markdown file.

    Supports the simple `key: value` form the bundle uses. Raises
    AssertionError if the file is missing a frontmatter block.
    """
    text = path.read_text(encoding='utf-8')
    assert text.startswith('---\n'), f"{path}: missing opening '---' fence"
    end = text.find('\n---\n', 4)
    assert end != -1, f"{path}: missing closing '---' fence"
    block = text[4:end]
    fm = {}
    for line in block.split('\n'):
        if not line.strip():
            continue
        assert ':' in line, f"{path}: malformed frontmatter line {line!r}"
        k, _, v = line.partition(':')
        fm[k.strip()] = v.strip()
    return fm


def markdown_links(text):
    """Yield (label, target) for every [label](target) link."""
    for m in re.finditer(r'\[([^\]]+)\]\(([^)]+)\)', text):
        yield m.group(1), m.group(2)


def bundle_version():
    return (ROOT / 'VERSION').read_text(encoding='utf-8').strip()


# ---------- version coherence ----------

def test_version_file_format():
    v = bundle_version()
    assert VERSION_RE.match(v), f"VERSION {v!r} does not match YYYY.MM[_revN]"


def test_plugin_json_version_matches():
    p = PLUGIN_DIR / '.claude-plugin' / 'plugin.json'
    data = json.loads(p.read_text(encoding='utf-8'))
    assert data.get('name') == 'llm-guidelines', f"{p}: wrong name {data.get('name')!r}"
    assert data.get('version') == bundle_version(), \
        f"{p}: version {data.get('version')!r} != VERSION {bundle_version()!r}"
    for required in ('description', 'license'):
        assert data.get(required), f"{p}: missing or empty {required!r}"


def test_marketplace_json_version_matches():
    p = ROOT / '.claude-plugin' / 'marketplace.json'
    data = json.loads(p.read_text(encoding='utf-8'))
    plugins = data.get('plugins') or []
    assert len(plugins) == 1, f"{p}: expected 1 plugin entry, got {len(plugins)}"
    entry = plugins[0]
    assert entry.get('name') == 'llm-guidelines', \
        f"{p}: wrong plugin name {entry.get('name')!r}"
    assert entry.get('version') == bundle_version(), \
        f"{p}: version {entry.get('version')!r} != VERSION {bundle_version()!r} " \
        f"(this is exactly the desync that broke 2026.05_rev10)"
    assert entry.get('source') == './plugins/llm-guidelines', \
        f"{p}: wrong source {entry.get('source')!r}"


def test_skill_md_versions_match():
    for name in ('explore', 'review'):
        skill = SKILLS_DIR / name / 'SKILL.md'
        fm = read_frontmatter(skill)
        assert fm.get('name') == name, \
            f"{skill}: frontmatter name {fm.get('name')!r} != {name!r}"
        assert fm.get('version') == bundle_version(), \
            f"{skill}: version {fm.get('version')!r} != VERSION {bundle_version()!r}"
        assert fm.get('description'), f"{skill}: missing description"
        assert fm.get('license'), f"{skill}: missing license"


# ---------- structural completeness ----------

def test_skills_and_commands_align():
    skill_names = {p.name for p in SKILLS_DIR.iterdir() if (p / 'SKILL.md').is_file()}
    command_names = {p.stem for p in COMMANDS_DIR.glob('*.md')}
    assert skill_names == command_names, \
        f"skills/ ({sorted(skill_names)}) and commands/ ({sorted(command_names)}) " \
        f"do not align — every command needs a backing skill and vice versa"
    assert skill_names == {'explore', 'review'}, \
        f"expected exactly {{explore, review}}, got {sorted(skill_names)}"


def test_shared_required_files_exist():
    required = [
        SHARED_DIR / 'scope.md',
        SHARED_DIR / 'checklist.md',
    ]
    for p in required:
        assert p.is_file(), f"missing shared file: {p.relative_to(ROOT)}"
    guidelines = list((SHARED_DIR / 'guidelines').glob('*.md'))
    assert len(guidelines) == 8, \
        f"expected 8 guideline files, got {len(guidelines)}: " \
        f"{[g.name for g in guidelines]}"
    study_types = list((SHARED_DIR / 'study-types').glob('*.md'))
    # 7 study types + advantages-and-challenges + two umbrella entries
    # ("llms-as-tools-for-software-engineering-researchers" and
    # "llms-as-tools-for-software-engineers") = 10 files total.
    assert len(study_types) == 10, \
        f"expected 10 study-type files, got {len(study_types)}: " \
        f"{[s.name for s in study_types]}"


# ---------- link health (internal only — no network) ----------

def test_skill_md_internal_links_resolve():
    """Every `../../shared/...` link in a SKILL.md must point to a real file."""
    broken = []
    for name in ('explore', 'review'):
        skill = SKILLS_DIR / name / 'SKILL.md'
        text = skill.read_text(encoding='utf-8')
        for label, target in markdown_links(text):
            # Strip optional anchor.
            path_part = target.split('#', 1)[0]
            if not path_part.startswith('../../shared/'):
                continue
            resolved = (skill.parent / path_part).resolve()
            if not resolved.is_file():
                broken.append(f"{skill.relative_to(ROOT)}: [{label}]({target}) -> "
                              f"{resolved} (not found)")
        # Also check the bare paths referenced in prose (backtick-quoted).
        # Only flag file references — directory pointers like
        # `../../shared/guidelines/` are valid prose, not links.
        for m in re.finditer(r'`(\.\./\.\./shared/[^`]+)`', text):
            ref = m.group(1)
            if '<' in ref or '*' in ref or ref.endswith('/'):
                continue
            resolved = (skill.parent / ref).resolve()
            if not resolved.is_file():
                broken.append(f"{skill.relative_to(ROOT)}: `{ref}` -> "
                              f"{resolved} (not found)")
    assert not broken, "broken internal links:\n  " + "\n  ".join(broken)


def test_no_absolute_website_links_leaked_into_shared():
    """The generator rewrites `/guidelines/<slug>/` etc. to relative paths
    inside shared/. A leak here means the rewrite step regressed."""
    leaks = []
    for md in SHARED_DIR.rglob('*.md'):
        text = md.read_text(encoding='utf-8')
        for label, target in markdown_links(text):
            if re.match(r'^/(guidelines|study-types|scope|checklist)/', target):
                leaks.append(f"{md.relative_to(ROOT)}: [{label}]({target})")
    assert not leaks, "absolute website paths leaked into bundle:\n  " + "\n  ".join(leaks)


# ---------- runner ----------

TESTS = [
    test_version_file_format,
    test_plugin_json_version_matches,
    test_marketplace_json_version_matches,
    test_skill_md_versions_match,
    test_skills_and_commands_align,
    test_shared_required_files_exist,
    test_skill_md_internal_links_resolve,
    test_no_absolute_website_links_leaked_into_shared,
]


def main():
    failed = 0
    for t in TESTS:
        try:
            t()
            print(f"PASS  {t.__name__}")
        except AssertionError as e:
            print(f"FAIL  {t.__name__}: {e}", file=sys.stderr)
            failed += 1
        except Exception as e:
            print(f"ERROR {t.__name__}: {type(e).__name__}: {e}", file=sys.stderr)
            failed += 1
    if failed:
        print(f"\n{failed}/{len(TESTS)} failure(s)", file=sys.stderr)
        return 1
    print(f"\nAll {len(TESTS)} tests passed.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
